Update package.json
added dependencies due to these errors on vercel:

sh: line 1: vite: command not found
Error: Command "npm run build" exited with 127